---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-scheduler
rules:
  # Permissions for reading nodes
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  # Permissions for managing pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete", "patch", "update"]
  # Permissions for pod binding
  - apiGroups: [""]
    resources: ["pods/binding"]
    verbs: ["create"]
  # Permissions for creating bindings
  - apiGroups: [""]
    resources: ["bindings"]
    verbs: ["create"]
  # Permissions for reading pod status
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get", "update", "patch"]
  # Permissions for events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-scheduler
subjects:
  - kind: ServiceAccount
    name: custom-scheduler
    namespace: kube-system

